### PR TITLE
Support_Vector_Machines.py

### PR DESCRIPTION
**Pull request by ASHMITA-DE**
Implementation of Support Vector Machines

### CODE REVIEW

**Comment by ASHMITA-DE** [comment]
Implementation of Support Vector Machines

**Review by iampujan — CHANGES_REQUESTED** [review]
Hi Ashmita,
Thank you for the contribution you are showing. I would love to see the files inside folder. Please upload with folder, so that it will be easy to find files and avoid mess.

**Comment by iampujan** [comment]
Also please add a readme.md file so that one can get clear concept of what the code is all about.

**Review by iampujan — APPROVED** [review]

**Comment by ASHMITA-DE** [comment]
> Hi Ashmita,
> Thank you for the contribution you are showing. I would love to see the files inside folder. Please upload with folder, so that it will be easy to find files and avoid mess.

Done

**Comment by iampujan** [comment]
Thanks. The merge is accepted. You can send another PR by keeping the submitted project inside either beginner or intermediate.

**Comment by ASHMITA-DE** [comment]
> Thanks. The merge is accepted. You can send another PR by keeping the submitted project inside either beginner or intermediate.

@iampujan , as per the new rules of Hacktoberfest 2020, could you please label this pull request as "hacktoberfest-accepted"? Thank you.

**Comment by ASHMITA-DE** [comment]
@iampujan, as per the new rules of Hacktoberfest 2020, could you please label this pull request as "hacktoberfest-accepted"? Thank you.

**Comment by iampujan** [comment]
done. thanks for reminding.

**Comment by ASHMITA-DE** [comment]
> done. thanks for reminding.

Thank you so much!

**Pull request merged**
